name: Alves Pryngler
favicon: null
layout_spectrum: 0.64357
typography_spectrum: 0.9987917530816048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8b0087'
    - '#004f89'
    - '#000000'
    - '#0000ff'
    - '#ff00ff'
  brandStrength: 0.875
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.8780317092314363
purpose: []
