name: Alves Pryngler
favicon: null
layout_spectrum: 0.8492884936276823
typography_spectrum: 0.9987917530816048
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9308845477644354
  lightness: 0.2064246190711856
  saturation: 0.1886384035460651
  rhythmicContrast: 0.8780317092314363
purpose: []
